# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR ORGANIZATION
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"POT-Creation-Date: 2014-05-29 18:34+GMT Summer Time\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=CHARSET\n"
"Content-Transfer-Encoding: ENCODING\n"
"Generated-By: pygettext.py 1.5\n"


#: packages.py:48
msgid "Installing pip.."
msgstr ""

#: packages.py:66
msgid ">> You need to run the setup steps first!"
msgstr ""

#: packages.py:69
msgid ">> Downloading package list.."
msgstr ""

#: packages.py:74
msgid ">> Error retrieving packages - %s"
msgstr ""

#: packages.py:78
msgid ">> Found %s package(s)."
msgstr ""

#: packages.py:126
msgid ">> No packages are installed. Nothing to do."
msgstr ""

#: packages.py:137
msgid ">> Unknown operation: %s"
msgstr ""

#: packages.py:144 packages.py:184
msgid "Name"
msgstr ""

#: packages.py:144 packages.py:184
msgid "Version"
msgstr ""

#: packages.py:145
msgid "Description"
msgstr ""

#: packages.py:164
msgid "Needed modules: %s"
msgstr ""

#: packages.py:172
msgid "Needed packages: %s"
msgstr ""

#: packages.py:196
msgid ">> Syntax: 'python packages.py install <package>'"
msgstr ""

#: packages.py:197 packages.py:239 packages.py:261
msgid ">> Try 'python packages.py -h' if you're stuck"
msgstr ""

#: packages.py:202
msgid ">> Installing package '%s'."
msgstr ""

#: packages.py:205
msgid ">> Package is already installed. Nothing to do."
msgstr ""

#: packages.py:211
msgid ">> Error installing package: %s"
msgstr ""

#: packages.py:218
msgid ">> Version %s installed successfully."
msgstr ""

#: packages.py:223
msgid ">> The following conflicts were found."
msgstr ""

#: packages.py:225
msgid "Directories"
msgstr ""

#: packages.py:229
msgid "Files"
msgstr ""

#: packages.py:232
msgid ">> These files were not modified but may be removed if you uninstall the package."
msgstr ""

#: packages.py:238
msgid ">> Syntax: 'python packages.py uninstall <package>'"
msgstr ""

#: packages.py:244
msgid ">> Uninstalling package '%s'."
msgstr ""

#: packages.py:247
msgid ">> Package is not installed. Nothing to do."
msgstr ""

#: packages.py:253
msgid ">> Error uninstalling package: %s"
msgstr ""

#: packages.py:255
msgid ">> Package uninstalled successfully."
msgstr ""

#: packages.py:260
msgid ">> Syntax: 'python packages.py info <package>'"
msgstr ""

#: packages.py:267
msgid ">> Package not found: %s"
msgstr ""

#: packages.py:270
msgid ">> Downloading information.."
msgstr ""

#: packages.py:276
msgid "=== Information ==="
msgstr ""

#: packages.py:277
msgid "Name: %s"
msgstr ""

#: packages.py:278
msgid "Latest version: v%s"
msgstr ""

#: packages.py:280
msgid "Installed: v%s"
msgstr ""

#: packages.py:281
msgid "Files: %s"
msgstr ""

#: packages.py:282
msgid "Documentation: %s"
msgstr ""

#: packages.py:284
msgid "=== Description ==="
msgstr ""

#: packages.py:286
msgid "=== Latest version ==="
msgstr ""

#: packages.py:287
msgid "Version: %s"
msgstr ""

#: packages.py:288
msgid "- %s other versions."
msgstr ""

#: packages.py:299 packages.py:358
msgid ">> Presuming everything installed okay, you should now be ready to run Ultros!"
msgstr ""

#: packages.py:329
msgid ">> There are some things pip can't install."
msgstr ""

#: packages.py:330
msgid ">> I will now attempt to download and install them manually."
msgstr ""

#: packages.py:331
msgid ">> Please be ready to click through dialogs!"
msgstr ""

#: packages.py:332
msgid ">> Please note, these files only work with Python 2.7!"
msgstr ""

#: packages.py:337
msgid ">> Files will be downloaded to %s"
msgstr ""

#: packages.py:339
msgid ">> OpenSSL will complain about a command prompt being open."
msgstr ""

#: packages.py:340
msgid ">> This is fine, just click \"OK\" to continue."
msgstr ""

#: packages.py:344
msgid ">> Downloading files for %s"
msgstr ""

#: plugins\auth\__init__.py:37 plugins\bridge\__init__.py:40
#: plugins\urls\__init__.py:51
msgid "Entered setup method."
msgstr ""

#: plugins\auth\__init__.py:44 plugins\bridge\__init__.py:47
#: plugins\urls\__init__.py:57
msgid "Error loading configuration!"
msgstr ""

#: plugins\auth\__init__.py:45 plugins\auth\__init__.py:50
#: plugins\bridge\__init__.py:48 plugins\bridge\__init__.py:53
msgid "Disabling.."
msgstr ""

#: plugins\auth\__init__.py:49
msgid "Unable to find config/plugins/auth.yml"
msgstr ""

#: plugins\auth\__init__.py:63
msgid "Unable to load permissions. They will be unavailable!"
msgstr ""

#: plugins\auth\__init__.py:70
msgid "Unable to set permissions handler!"
msgstr ""

#: plugins\auth\__init__.py:81
msgid "Unable to load user accounts. They will be unavailable!"
msgstr ""

#: plugins\auth\__init__.py:88
msgid "Unable to set auth handler!"
msgstr ""

#: plugins\auth\__init__.py:90
msgid "Registering commands."
msgstr ""

#: plugins\auth\__init__.py:103
msgid "Command: %s"
msgstr ""

#: plugins\auth\__init__.py:108 plugins\auth\__init__.py:119
msgid "[REDACTED]"
msgstr ""

#: plugins\auth\__init__.py:130
msgid "Usage: {CHARS}login <username> <password>"
msgstr ""

#: plugins\auth\__init__.py:133
msgid "You're already logged in. Try logging out first!"
msgstr ""

#: plugins\auth\__init__.py:141
msgid "%s failed to login as %s"
msgstr ""

#: plugins\auth\__init__.py:143
msgid "Invalid username or password!"
msgstr ""

#: plugins\auth\__init__.py:145
msgid "%s logged in as %s"
msgstr ""

#: plugins\auth\__init__.py:147
msgid "You are now logged in as %s."
msgstr ""

#: plugins\auth\__init__.py:154
msgid "You have been logged out successfully."
msgstr ""

#: plugins\auth\__init__.py:156
msgid "You're not logged in."
msgstr ""

#: plugins\auth\__init__.py:162
msgid "Usage: {CHARS}register <username> <password>"
msgstr ""

#: plugins\auth\__init__.py:168
msgid "You can't create an account in a channel."
msgstr ""

#: plugins\auth\__init__.py:169
msgid "Don't use this command in a channel!"
msgstr ""

#: plugins\auth\__init__.py:170
msgid "You should only use it in a private message."
msgstr ""

#: plugins\auth\__init__.py:171
msgid "For your security, the password you used has been blacklisted."
msgstr ""

#: plugins\auth\__init__.py:177
msgid "That username already exists!"
msgstr ""

#: plugins\auth\__init__.py:181 plugins\auth\__init__.py:214
msgid "That password has been blacklisted. Try another!"
msgstr ""

#: plugins\auth\__init__.py:186
msgid "Your account has been created and you will now be logged in. Thanks for registering!"
msgstr ""

#: plugins\auth\__init__.py:192
msgid "Something went wrong when creating your account! You should ask the bot operators about this."
msgstr ""

#: plugins\auth\__init__.py:200
msgid "Usage: {CHARS}passwd <old password> <new password>"
msgstr ""

#: plugins\auth\__init__.py:204
msgid "You must be logged in to change your password."
msgstr ""

#: plugins\auth\__init__.py:219
msgid "Your password has been changed successfully."
msgstr ""

#: plugins\auth\__init__.py:221
msgid "Old password incorrect - please try again!"
msgstr ""

#: plugins\auth\__init__.py:222
msgid "User %s failed to change the password for %s"
msgstr ""

#: plugins\auth\auth_handler.py:33
msgid "Created password blacklist with the 20 most popular passwords of 2013."
msgstr ""

#: plugins\auth\auth_handler.py:39 plugins\auth\auth_handler.py:55
#: plugins\auth\auth_handler.py:65 plugins\auth\auth_handler.py:69
#: plugins\auth\auth_handler.py:70
msgid "superadmin"
msgstr ""

#: plugins\auth\auth_handler.py:40
msgid "Superadmin account exists!"
msgstr ""

#: plugins\auth\auth_handler.py:41
msgid "You should remove this account as soon as possible!"
msgstr ""

#: plugins\auth\auth_handler.py:44
msgid "Generating a default auth account and password."
msgstr ""

#: plugins\auth\auth_handler.py:46
msgid "You will need to either use this to add permissions to your user account, or just create an account and edit the permissions file."
msgstr ""

#: plugins\auth\auth_handler.py:50
msgid "Remember to delete this account when you've created your own admin account!"
msgstr ""

#: plugins\auth\auth_handler.py:58
msgid "Super admin username: superadmin"
msgstr ""

#: plugins\auth\auth_handler.py:59
msgid "Super admin password: %s"
msgstr ""

#: plugins\auth\auth_handler.py:66
msgid "Unable to create permissions section for the superadmin account!"
msgstr ""

#: plugins\auth\auth_handler.py:72
msgid "Unable to set 'superadmin' flag on the superadmin account!"
msgstr ""

#: plugins\auth\auth_handler.py:75
msgid "Unable to set permissions for the superadmin account as the bundled permissions system isn't being used."
msgstr ""

#: plugins\auth\auth_handler.py:78
msgid "Please do this manually!"
msgstr ""

#: plugins\auth\permissions_handler.py:69
msgid "CHECK | Permis: %s"
msgstr ""

#: plugins\auth\permissions_handler.py:70
msgid "CHECK | Caller: %s"
msgstr ""

#: plugins\auth\permissions_handler.py:71
msgid "CHECK | Source: %s"
msgstr ""

#: plugins\auth\permissions_handler.py:72
msgid "CHECK | Protoc: %s"
msgstr ""

#: plugins\auth\permissions_handler.py:76
msgid "CHECK | Caller is None."
msgstr ""

#: plugins\auth\permissions_handler.py:81
msgid "CHECK | Authorized: %s"
msgstr ""

#: plugins\auth\permissions_handler.py:89
msgid "CHECK | Not authorized."
msgstr ""

#: plugins\auth\permissions_handler.py:111
msgid "User created: %s"
msgstr ""

#: plugins\auth\permissions_handler.py:132
msgid "Option %s set to %s for user %s."
msgstr ""

#: plugins\auth\permissions_handler.py:319
msgid "Inheritance must either be a string or None"
msgstr ""

#: plugins\auth\permissions_handler.py:385
msgid "Checking group perms..."
msgstr ""

#: plugins\auth\permissions_handler.py:386
msgid "GROUP | %s"
msgstr ""

#: plugins\auth\permissions_handler.py:387
msgid "PERMI | %s"
msgstr ""

#: plugins\auth\permissions_handler.py:388
msgid "SOURC | %s"
msgstr ""

#: plugins\auth\permissions_handler.py:389
msgid "PROTO | %s"
msgstr ""

#: plugins\bridge\__init__.py:52
msgid "Unable to find config/plugins/bridge.yml"
msgstr ""

#: plugins\bridge\__init__.py:193
msgid "Checking rule: %s - %s"
msgstr ""

#: plugins\bridge\__init__.py:198
msgid "Protocol doesn't match."
msgstr ""

#: plugins\bridge\__init__.py:202
msgid "Target protocol doesn't exist."
msgstr ""

#: plugins\bridge\__init__.py:209
msgid "Function was called with relaying from users disabled."
msgstr ""

#: plugins\bridge\__init__.py:213
msgid "Target type isn't a user."
msgstr ""

#: plugins\bridge\__init__.py:217
msgid "Target type isn't a Channel."
msgstr ""

#: plugins\bridge\__init__.py:221
msgid "Target name doesn't match the source."
msgstr ""

#: plugins\bridge\__init__.py:225
msgid "Target isn't a known type."
msgstr ""

#: plugins\bridge\__init__.py:229
msgid "Function was called with relaying to users disabled."
msgstr ""

#: plugins\bridge\__init__.py:243
msgid "Not relaying message as the format string was empty or missing."
msgstr ""

#: plugins\bridge\generic.py:20
msgid "Setup method needs to be implemented!"
msgstr ""

#: plugins\control\__init__.py:36
msgid "Usage: {CHARS}join <channel>"
msgstr ""

#: plugins\control\__init__.py:43 plugins\control\__init__.py:60
#: plugins\control\__init__.py:76 plugins\control\__init__.py:93
#: plugins\control\__init__.py:110 run.py:69
msgid "Done!"
msgstr ""

#: plugins\control\__init__.py:45
msgid "Unable to join channel. Does this protocol support joining channels?"
msgstr ""

#: plugins\control\__init__.py:48 plugins\control\__init__.py:65
msgid "This protocol doesn't support channels."
msgstr ""

#: plugins\control\__init__.py:53
msgid "Usage: {CHARS}leave <channel>"
msgstr ""

#: plugins\control\__init__.py:62
msgid "Unable to leave channel. Does this protocol support leaving channels?"
msgstr ""

#: plugins\control\__init__.py:70
msgid "Usage: {CHARS}raw <data>"
msgstr ""

#: plugins\control\__init__.py:78
msgid "This protocol doesn't support sending raw data."
msgstr ""

#: plugins\control\__init__.py:84
msgid "Usage: {CHARS}say <target> <message>"
msgstr ""

#: plugins\control\__init__.py:95
msgid "This protocol doesn't support sending messages."
msgstr ""

#: plugins\control\__init__.py:101
msgid "Usage: {CHARS}action <target> <message>"
msgstr ""

#: plugins\control\__init__.py:112
msgid "This protocol doesn't support sending actions."
msgstr ""

#: plugins\control\__init__.py:118
msgid "Usage: {CHARS}func <function> <data>"
msgstr ""

#: plugins\control\__init__.py:140
msgid "No such function: %s"
msgstr ""

#: plugins\control\__init__.py:144
msgid "Error running 'func' command!"
msgstr ""

#: plugins\control\__init__.py:145 plugins\factoids\__init__.py:566
#: plugins\urls\__init__.py:289 plugins\urls\__init__.py:321
msgid "Error: %s"
msgstr ""

#: plugins\control\__init__.py:147
msgid "Done! Call returned: %s"
msgstr ""

#: plugins\debug\__init__.py:50
msgid "[DEBUG] %s"
msgstr ""

#: plugins\debug\__init__.py:71
msgid "Syntax error: %s"
msgstr ""

#: plugins\debug\__init__.py:74
msgid "Invalid literal: %s"
msgstr ""

#: plugins\debug\__init__.py:77 plugins\debug\__init__.py:83
msgid "%s"
msgstr ""

#: plugins\debug\monitors.py:25
msgid "Running collection.."
msgstr ""

#: plugins\debug\monitors.py:33
msgid "Starting uncollectable objects monitor."
msgstr ""

#: plugins\debug\monitors.py:37
msgid "Uncollectable object cycle in gc.garbage!"
msgstr ""

#: plugins\debug\monitors.py:39
msgid "Parents:"
msgstr ""

#: plugins\debug\monitors.py:42
msgid "Children:"
msgstr ""

#: plugins\debug\monitors.py:63
msgid "dict with keys %r @ 0x%x"
msgstr ""

#: plugins\dialectizer\__init__.py:79
msgid "This command only applies to channels."
msgstr ""

#: plugins\dialectizer\__init__.py:82
msgid "Usage: {CHARS}dialectizer <dialectizer>"
msgstr ""

#: plugins\dialectizer\__init__.py:83
msgid "Available dialectizers: %s"
msgstr ""

#: plugins\dialectizer\__init__.py:96
msgid "Unknown dialectizer: %s"
msgstr ""

#: plugins\dialectizer\__init__.py:100
msgid "Dialectizer set to '%s'"
msgstr ""

#: plugins\factoids\__init__.py:114
msgid "Checking for permission: '%s'"
msgstr ""

#: plugins\factoids\__init__.py:137 plugins\factoids\__init__.py:141
#: plugins\factoids\__init__.py:146
msgid "Invalid args"
msgstr ""

#: plugins\factoids\__init__.py:157
msgid "'%s' is not a valid location"
msgstr ""

#: plugins\factoids\__init__.py:161
msgid "'channel' location can only be used inside a channel"
msgstr ""

#: plugins\factoids\__init__.py:242 plugins\factoids\__init__.py:300
msgid "Factoid '%s' does not exist"
msgstr ""

#: plugins\factoids\__init__.py:254
msgid "Getting factoid params: factoid_key = '%s', location = '%s', protocol = '%s', channel = '%s'"
msgstr ""

#: plugins\factoids\__init__.py:262
msgid "Location is None - getting all factoids with key '%s'"
msgstr ""

#: plugins\factoids\__init__.py:275
msgid "Match found (channel)!"
msgstr ""

#: plugins\factoids\__init__.py:280
msgid "Match found (protocol)!"
msgstr ""

#: plugins\factoids\__init__.py:285
msgid "Match found (global)!"
msgstr ""

#: plugins\factoids\__init__.py:332 plugins\factoids\__init__.py:357
#: plugins\factoids\__init__.py:385 plugins\factoids\__init__.py:409
msgid "User does not have required permission"
msgstr ""

#: plugins\factoids\__init__.py:427
msgid "Invalid location given - possible locations are: channel, protocol, global"
msgstr ""

#: plugins\factoids\__init__.py:430
msgid "You must do that in a channel"
msgstr ""

#: plugins\factoids\__init__.py:432
msgid "You don't have permission to do that"
msgstr ""

#: plugins\factoids\__init__.py:434
msgid "That factoid doesn't exist"
msgstr ""

#: plugins\factoids\__init__.py:461 plugins\factoids\__init__.py:475
msgid "Usage: %s <location> <factoid> <info>"
msgstr ""

#: plugins\factoids\__init__.py:466 plugins\factoids\__init__.py:728
#: plugins\factoids\__init__.py:787 plugins\factoids\__init__.py:848
msgid "Factoid added"
msgstr ""

#: plugins\factoids\__init__.py:480 plugins\factoids\__init__.py:747
#: plugins\factoids\__init__.py:807 plugins\factoids\__init__.py:868
msgid "Factoid set"
msgstr ""

#: plugins\factoids\__init__.py:488
msgid "Usage: %s <location> <factoid>"
msgstr ""

#: plugins\factoids\__init__.py:495 plugins\factoids\__init__.py:765
#: plugins\factoids\__init__.py:826 plugins\factoids\__init__.py:887
msgid "Factoid deleted"
msgstr ""

#: plugins\factoids\__init__.py:509
msgid "Usage: %s [location] <factoid>"
msgstr ""

#: plugins\factoids\__init__.py:526
msgid "Registering web routes.."
msgstr ""

#: plugins\factoids\__init__.py:542
msgid "<th>Location</th>"
msgstr ""

#: plugins\factoids\__init__.py:543
msgid "<th>Protocol</th>"
msgstr ""

#: plugins\factoids\__init__.py:544
msgid "<th>Channel</th>"
msgstr ""

#: plugins\factoids\__init__.py:545
msgid "<th>Name</th>"
msgstr ""

#: plugins\factoids\__init__.py:546
msgid "<th>Content</th>"
msgstr ""

#: plugins\factoids\__init__.py:560 plugins\factoids\__init__.py:566
#: plugins\factoids\__init__.py:567 plugins\factoids\__init__.py:591
#: plugins\factoids\__init__.py:592
msgid "Factoids"
msgstr ""

#: plugins\factoids\__init__.py:575
msgid "WEB | Checking permissions.."
msgstr ""

#: plugins\factoids\__init__.py:578
msgid "WEB | User does not have permission. Are they logged in?"
msgstr ""

#: plugins\factoids\__init__.py:585
msgid "WEB | Yup. They must not have permission."
msgstr ""

#: plugins\factoids\__init__.py:586
msgid "WEB | Presenting error.."
msgstr ""

#: plugins\factoids\__init__.py:589
msgid "Error: You do not have permission to list the factoids."
msgstr ""

#: plugins\factoids\__init__.py:594
msgid "WEB | User has permission."
msgstr ""

#: plugins\factoids\__init__.py:652
msgid "Usage: ?? <factoid>"
msgstr ""

#: plugins\factoids\__init__.py:671
msgid "Usage: ?< <factoid>"
msgstr ""

#: plugins\factoids\__init__.py:690
msgid "Usage: ?> <user> <factoid>"
msgstr ""

#: plugins\factoids\__init__.py:698
msgid "Unable to find that user."
msgstr ""

#: plugins\factoids\__init__.py:719
msgid "Usage: ??+ <factoid> <info>"
msgstr ""

#: plugins\factoids\__init__.py:738
msgid "Usage: ??~ <factoid> <info>"
msgstr ""

#: plugins\factoids\__init__.py:757
msgid "Usage: ??- <factoid>"
msgstr ""

#: plugins\factoids\__init__.py:778
msgid "Usage: !?+ <factoid> <info>"
msgstr ""

#: plugins\factoids\__init__.py:798
msgid "Usage: !?~ <factoid> <info>"
msgstr ""

#: plugins\factoids\__init__.py:818
msgid "Usage: !?- <factoid>"
msgstr ""

#: plugins\factoids\__init__.py:839
msgid "Usage: @?+ <factoid> <info>"
msgstr ""

#: plugins\factoids\__init__.py:859
msgid "Usage: @?~ <factoid> <info>"
msgstr ""

#: plugins\factoids\__init__.py:879
msgid "Usage: @?- <factoid>"
msgstr ""

#: plugins\urls\__init__.py:60
msgid "Unable to find config/plugins/urls.yml"
msgstr ""

#: plugins\urls\__init__.py:65
msgid "Spoofing: %s"
msgstr ""

#: plugins\urls\__init__.py:149
msgid "Error catching URL"
msgstr ""

#: plugins\urls\__init__.py:153
msgid "Title: %s"
msgstr ""

#: plugins\urls\__init__.py:196
msgid "Unknown target type: %s [%s]"
msgstr ""

#: plugins\urls\__init__.py:203
msgid "This command can only be used in a channel."
msgstr ""

#: plugins\urls\__init__.py:206
msgid "Usage: {CHARS}urls <setting> <value>"
msgstr ""

#: plugins\urls\__init__.py:207
msgid "Operations: set <on/off> - Enable or disable title parsing for the current channel"
msgstr ""

#: plugins\urls\__init__.py:209
msgid "shortener <name> - Set which URL shortener to use for the current channel"
msgstr ""

#: plugins\urls\__init__.py:212
msgid "Shorteners: %s"
msgstr ""

#: plugins\urls\__init__.py:237 plugins\urls\__init__.py:241
msgid "on"
msgstr ""

#: plugins\urls\__init__.py:237 plugins\urls\__init__.py:243
msgid "off"
msgstr ""

#: plugins\urls\__init__.py:238
msgid "Usage: {CHARS}urls set <on|off>"
msgstr ""

#: plugins\urls\__init__.py:246
msgid "Title passing for %s turned %s."
msgstr ""

#: plugins\urls\__init__.py:253
msgid "URL shortener for %s set to %s."
msgstr ""

#: plugins\urls\__init__.py:256
msgid "Unknown shortener: %s"
msgstr ""

#: plugins\urls\__init__.py:258
msgid "Unknown operation: '%s'."
msgstr ""

#: plugins\urls\__init__.py:263
msgid "Unable to shorten using handler %s. Poke thebot owner!"
msgstr ""

#: plugins\urls\__init__.py:268
msgid "Error shortening url with handler %s: %s"
msgstr ""

#: plugins\urls\__init__.py:276
msgid "Usage: {CHARS}shorten [url]"
msgstr ""

#: plugins\urls\__init__.py:288 plugins\urls\__init__.py:320
msgid "Error fetching short URL."
msgstr ""

#: plugins\urls\__init__.py:295
msgid "Nobody's pasted a URL here yet!"
msgstr ""

#: plugins\urls\__init__.py:304
msgid "Shortener '%s' not found - please set a new one!"
msgstr ""

#: plugins\urls\__init__.py:330
msgid "Url: %s"
msgstr ""

#: plugins\urls\__init__.py:342 plugins\urls\__init__.py:399
msgid "Prevented a portscan: %s"
msgstr ""

#: plugins\urls\__init__.py:354 plugins\urls\__init__.py:411
msgid "Error running handler, parsing title normally."
msgstr ""

#: plugins\urls\__init__.py:357
msgid "Parsed domain: %s"
msgstr ""

#: plugins\urls\__init__.py:361
msgid "Custom spoofing for this domain found."
msgstr ""

#: plugins\urls\__init__.py:364
msgid "Spoofing user-agent: %s"
msgstr ""

#: plugins\urls\__init__.py:368
msgid "Not spoofing user-agent."
msgstr ""

#: plugins\urls\__init__.py:370
msgid "Spoofing Firefox as usual."
msgstr ""

#: plugins\urls\__init__.py:377
msgid "Info: %s"
msgstr ""

#: plugins\urls\__init__.py:388 plugins\urls\__init__.py:471
msgid "URL: %s"
msgstr ""

#: plugins\urls\__init__.py:389
msgid "Domain: %s"
msgstr ""

#: plugins\urls\__init__.py:430
msgid "Content-type: %s"
msgstr ""

#: plugins\urls\__init__.py:433
msgid "Content-type is not allowed."
msgstr ""

#: plugins\urls\__init__.py:448
msgid "Error parsing title."
msgstr ""

#: plugins\urls\__init__.py:457
msgid "Result (SQL): %s"
msgstr ""

#: plugins\urls\__init__.py:472
msgid "Handler: %s"
msgstr ""

#: plugins\urls\__init__.py:478
msgid "Domain should not start with 'www.'"
msgstr ""

#: plugins\urls\__init__.py:480
msgid "Handler registered for '%s': %s"
msgstr ""

#: plugins\urls\__init__.py:488
msgid "Shortener '%s' registered: %s"
msgstr ""

#: plugins\urls\catcher.py:43
msgid "No catcher section in config."
msgstr ""

#: plugins\urls\catcher.py:49
msgid "Catcher disabled via config."
msgstr ""

#: plugins\urls\catcher.py:75
msgid "Broken pipe has occurred more than three times in a row!"
msgstr ""

#: plugins\urls\catcher.py:105
msgid "Created table."
msgstr ""

#: plugins\urls\catcher.py:106
msgid "Failed to create table: %s"
msgstr ""

#: plugins\urls\catcher.py:110
msgid "Looking for SQL in %s"
msgstr ""

#: plugins\urls\catcher.py:116
msgid "No SQL found for dialect '%s'."
msgstr ""

#: plugins\urls\catcher.py:157
msgid "Failed to insert URL: %s"
msgstr ""

#: run.py:56
msgid "Attempting to update.."
msgstr ""

#: run.py:71
msgid "Error updating: %s"
msgstr ""

#: run.py:100
msgid "Starting up, version \"%s\""
msgstr ""

#: run.py:109
msgid "Runtime error - process cannot continue!"
msgstr ""

#: run.py:122
msgid "Press enter to exit."
msgstr ""

#: system\command_manager.py:92
msgid "Object '%s' tried to register command '%s' butit's already been registered by object '%s'."
msgstr ""

#: system\command_manager.py:100
msgid "Registering command: %s (%s)"
msgstr ""

#: system\command_manager.py:112
msgid "Failed to register command alias '%s' as it already belongs to another command."
msgstr ""

#: system\command_manager.py:117
msgid "Registering alias: %s -> %s (%s)"
msgstr ""

#: system\command_manager.py:134
msgid "Unregistered command: %s"
msgstr ""

#: system\command_manager.py:236
msgid "Auth handler %s is already registered."
msgstr ""

#: system\command_manager.py:256
msgid "Two plugins are trying to provide permissions handlers. Only the first will be used!"
msgstr ""

#: system\decorators.py:197
msgid "%s() takes at most %s non-keyword arguments (%s given)"
msgstr ""

#: system\decorators.py:203
msgid "Unexpected keyword argument '%s' for %s()"
msgstr ""

#: system\decorators.py:209
msgid "Parameter '%s' is not %s"
msgstr ""

#: system\event_manager.py:114
msgid "Plugin '%s' has already registered a handler for the '%s' callback"
msgstr ""

#: system\event_manager.py:128
msgid "Adding callback: %s"
msgstr ""

#: system\event_manager.py:288
msgid "Running callback: %s"
msgstr ""

#: system\event_manager.py:292
msgid "Not running, filter function returned False."
msgstr ""

#: system\event_manager.py:297
msgid "Not running event, filter is not actually a function. Bug the developers of the %s plugin about it!"
msgstr ""

#: system\event_manager.py:302
msgid "Value: %s"
msgstr ""

#: system\event_manager.py:308
msgid "Not running, event is cancelled and handler doesn't accept cancelled events"
msgstr ""

#: system\event_manager.py:315
msgid "Error running callback '%s': %s"
msgstr ""

#: system\factory.py:67
msgid "Entering setup method."
msgstr ""

#: system\factory.py:71
msgid "First-time setup; not reloading."
msgstr ""

#: system\factory.py:75
msgid "Reloading module."
msgstr ""

#: system\factory.py:80
msgid "Unable to import protocol %s for %s"
msgstr ""

#: system\factory.py:89
msgid "Protocol does not subclass the generic protocol class!"
msgstr ""

#: system\factory.py:97
msgid "Error shutting down"
msgstr ""

#: system\factory.py:117
msgid "Error calling \"connection lost\" callback"
msgstr ""

#: system\factory.py:123
msgid "Lost connection: %s"
msgstr ""

#: system\factory.py:126 system\factory.py:153
msgid "Unable to connect after %s attempts, aborting."
msgstr ""

#: system\factory.py:130 system\factory.py:157
msgid "Reconnecting after %s seconds (attempt %s/%s)"
msgstr ""

#: system\factory.py:144
msgid "Error calling \"connection failed\" callback"
msgstr ""

#: system\factory.py:150
msgid "Connection failed: %s"
msgstr ""

#: system\factory.py:166
msgid "Error calling \"connected\" callback"
msgstr ""

#: system\factory_manager.py:89
msgid "It seems like no protocols are loaded. Shutting down.."
msgstr ""

#: system\factory_manager.py:96
msgid "Error setting up metrics."
msgstr ""

#: system\factory_manager.py:108
msgid "Manager is already running!"
msgstr ""

#: system\factory_manager.py:116
msgid "Error while unloading!"
msgstr ""

#: system\factory_manager.py:133
msgid "Loading global configuration.."
msgstr ""

#: system\factory_manager.py:135
msgid "Main configuration not found! Please correct this and try again."
msgstr ""

#: system\factory_manager.py:140 system\factory_manager.py:145
msgid "Unable to load main configuration at config/settings.yml"
msgstr ""

#: system\factory_manager.py:142
msgid "Please check that this file exists."
msgstr ""

#: system\factory_manager.py:156
msgid "Loading plugins.."
msgstr ""

#: system\factory_manager.py:158
msgid "Configured plugins: %s"
msgstr ""

#: system\factory_manager.py:161
msgid "Collecting plugins.."
msgstr ""

#: system\factory_manager.py:172
msgid "Loading plugins that have no dependencies first."
msgstr ""

#: system\factory_manager.py:177 system\factory_manager.py:198
msgid "Checking if plugin '%s' is configured to load.."
msgstr ""

#: system\factory_manager.py:180 system\factory_manager.py:201
msgid "Attempting to load plugin: %s"
msgstr ""

#: system\factory_manager.py:184 system\factory_manager.py:223
msgid "Error detected while loading plugin."
msgstr ""

#: system\factory_manager.py:187 system\factory_manager.py:226
msgid "Plugin already loaded."
msgstr ""

#: system\factory_manager.py:189 system\factory_manager.py:228
msgid "Plugin doesn't exist."
msgstr ""

#: system\factory_manager.py:192 system\factory_manager.py:230
msgid "Plugin dependency is missing."
msgstr ""

#: system\factory_manager.py:195
msgid "Loading plugins that have dependencies."
msgstr ""

#: system\factory_manager.py:208 system\factory_manager.py:213
msgid "Dependency loop detected while loading: %s"
msgstr ""

#: system\factory_manager.py:210 system\factory_manager.py:215
msgid "This plugin will not be available."
msgstr ""

#: system\factory_manager.py:235
msgid "No plugins are configured to load."
msgstr ""

#: system\factory_manager.py:265
msgid "Dependencies for %s: %s"
msgstr ""

#: system\factory_manager.py:269
msgid "Error loading plugin %s: the plugin relies on another plugin (%s), but it is not present."
msgstr ""

#: system\factory_manager.py:280
msgid "Unable to load dependency: %s"
msgstr ""

#: system\factory_manager.py:286
msgid "Loading plugin: %s"
msgstr ""

#: system\factory_manager.py:288
msgid "Location: %s"
msgstr ""

#: system\factory_manager.py:292
msgid "Running setup method.."
msgstr ""

#: system\factory_manager.py:295
msgid "Unable to load plugin: %s v%s"
msgstr ""

#: system\factory_manager.py:301
msgid "Loaded plugin: %s v%s"
msgstr ""

#: system\factory_manager.py:304
msgid "Licensing: %s"
msgstr ""

#: system\factory_manager.py:326
msgid "Setting up protocols.."
msgstr ""

#: system\factory_manager.py:329
msgid "Setting up protocol: %s"
msgstr ""

#: system\factory_manager.py:335
msgid "Protocol is already loaded."
msgstr ""

#: system\factory_manager.py:337
msgid "Unable to find protocol configuration."
msgstr ""

#: system\factory_manager.py:340
msgid "Error detected while loading protocol."
msgstr ""

#: system\factory_manager.py:343
msgid "Error detected while setting up protocol."
msgstr ""

#: system\factory_manager.py:379
msgid "Unable to load configuration for the '%s' protocol."
msgstr ""

#: system\factory_manager.py:391
msgid "Unable to create factory for the '%s' protocol!"
msgstr ""

#: system\factory_manager.py:414
msgid "Error disabling plugin: %s"
msgstr ""

#: system\factory_manager.py:438
msgid "Error shutting down protocol %s"
msgstr ""

#: system\factory_manager.py:451
msgid "Unloading protocol: %s"
msgstr ""

#: system\factory_manager.py:454
msgid "Unloading plugin: %s"
msgstr ""

#: system\metrics.py:107
msgid "We couldn't find a \"metrics\" option in your settings.yml file!"
msgstr ""

#: system\metrics.py:111
msgid "Metrics will default to being turned on. If this is not what you want, please create \"metrics\" option in your settings and set it to \"off\"."
msgstr ""

#: system\metrics.py:116
msgid "If you want to keep metrics enabled, set the option to \"on\"."
msgstr ""

#: system\metrics.py:120
msgid "This warning will be shown on every startup until the option has been set."
msgstr ""

#: system\metrics.py:132
msgid "Error getting UUID"
msgstr ""

#: system\metrics.py:141 system\metrics.py:145
msgid "Metrics are disabled."
msgstr ""

#: system\metrics.py:152
msgid "Firing task."
msgstr ""

#: system\metrics.py:155
msgid "Submitting metrics."
msgstr ""

#: system\metrics.py:168 system\metrics.py:182
msgid "Submitted. Result: %s"
msgstr ""

#: system\metrics.py:171
msgid "Error submitting metrics: %s"
msgstr ""

#: system\metrics.py:174
msgid "Error submitting metrics"
msgstr ""

#: system\metrics.py:176
msgid "Submitting disable message."
msgstr ""

#: system\metrics.py:185
msgid "Error submitting disable message: %s"
msgstr ""

#: system\metrics.py:188
msgid "Error submitting disable message"
msgstr ""

#: system\metrics.py:195
msgid "Submitting destruction message."
msgstr ""

#: system\metrics.py:203
msgid "Metrics data has been removed from the server."
msgstr ""

#: system\metrics.py:206
msgid "Unknown UUID, data was already removed from the server."
msgstr ""

#: system\metrics.py:209
msgid "Error submitting destruction message"
msgstr ""

#: system\metrics.py:217
msgid "Unknown status: %s"
msgstr ""

#: system\plugin.py:93
msgid "Setup method not defined!"
msgstr ""

#: system\plugin_manager.py:177 system\plugin_manager.py:183
#: system\plugin_manager.py:187 system\plugin_manager.py:190
msgid "Unknown"
msgstr ""

#: system\plugin_manager.py:181 system\plugin_manager.py:189
msgid "None"
msgstr ""

#: system\plugin_manager.py:214
msgid "Could not parse the plugin file '%s' (exception raised was '%s')"
msgstr ""

#: system\plugin_manager.py:220
msgid "Plugin info file has no 'core' section (in '%s')"
msgstr ""

#: system\plugin_manager.py:224
msgid "Plugin info file has no 'name' or 'module' section (in '%s')"
msgstr ""

#: system\plugin_manager.py:232
msgid "Plugin name contains forbidden character: %s (in '%s')"
msgstr ""

#: system\plugin_manager.py:364
msgid "Two incompatible arguments (%s) provided: 'plugin_info_ext' and 'plugin_locator'). Ignoring 'plugin_info_ext'."
msgstr ""

#: system\protocols\generic\channel.py:16 system\protocols\generic\user.py:18
msgid "This method must be overridden"
msgstr ""

#: system\protocols\generic\protocol.py:114
#: system\protocols\generic\protocol.py:121
#: system\protocols\generic\protocol.py:161
#: system\protocols\generic\protocol.py:169
#: system\protocols\generic\protocol.py:183
#: system\protocols\generic\protocol.py:197
#: system\protocols\generic\protocol.py:214
msgid "This function needs to be implemented!"
msgstr ""

#: system\protocols\generic\protocol.py:133
#: system\protocols\generic\protocol.py:148
msgid "This function needs to be implemented."
msgstr ""

#: system\protocols\irc\channel.py:29 system\protocols\mumble\channel.py:39
msgid "Tried to remove non-existent user \"%s\" from channel \"%s\""
msgstr ""

#: system\protocols\irc\channel.py:44
msgid "Tried to remove non-existent mode \"%s\" from channel \"%s\""
msgstr ""

#: system\protocols\irc\protocol.py:92
msgid "Setting up.."
msgstr ""

#: system\protocols\irc\protocol.py:100
msgid "Unable to import the SSL library. SSL will not be available."
msgstr ""

#: system\protocols\irc\protocol.py:127
msgid "No ctcp_flood_protection block in config - using default values"
msgstr ""

#: system\protocols\irc\protocol.py:134
msgid "Config doesn't contain network/password entry"
msgstr ""

#: system\protocols\irc\protocol.py:146
msgid "Binding to address: %s"
msgstr ""

#: system\protocols\irc\protocol.py:153
msgid "SSL is not available but was requested in the configuration."
msgstr ""

#: system\protocols\irc\protocol.py:155
msgid "IRC will be unavailable until SSL is fixed or is disabled in the configuration."
msgstr ""

#: system\protocols\irc\protocol.py:164
msgid "Connecting with SSL"
msgstr ""

#: system\protocols\irc\protocol.py:174
msgid "Connecting without SSL"
msgstr ""

#: system\protocols\irc\protocol.py:187
msgid "Protocol shutdown"
msgstr ""

#: system\protocols\irc\protocol.py:204
msgid "SERVER -> %s"
msgstr ""

#: system\protocols\irc\protocol.py:264
msgid "Scheduling Deferreds for signing on and joining channels"
msgstr ""

#: system\protocols\irc\protocol.py:273
msgid "Joined channel: %s"
msgstr ""

#: system\protocols\irc\protocol.py:283
msgid "Parted channel: %s"
msgstr ""

#: system\protocols\irc\protocol.py:293
msgid "Kicked from %s by %s: %s"
msgstr ""

#: system\protocols\irc\protocol.py:310 system\protocols\irc\protocol.py:316
msgid "Rejoining in %s seconds.."
msgstr ""

#: system\protocols\irc\protocol.py:324
msgid "Nick changed to %s"
msgstr ""

#: system\protocols\irc\protocol.py:368
#: system\protocols\mumble\protocol.py:699
msgid "%s is not authorized to use the %s command"
msgstr ""

#: system\protocols\irc\protocol.py:372
#: system\protocols\mumble\protocol.py:703
msgid "Command not found: %s"
msgstr ""

#: system\protocols\irc\protocol.py:375
#: system\protocols\mumble\protocol.py:706
msgid "An error occured while running the %s command: %s"
msgstr ""

#: system\protocols\irc\protocol.py:389
msgid "Message from irregular user: %s"
msgstr ""

#: system\protocols\irc\protocol.py:423
msgid "Notice from irregular user: %s"
msgstr ""

#: system\protocols\irc\protocol.py:464
msgid "First CTCP in over %s seconds - resetting counter"
msgstr ""

#: system\protocols\irc\protocol.py:474
msgid "Too many CTCPs received - blocking"
msgstr ""

#: system\protocols\irc\protocol.py:484
msgid "CTCP from irregular user: %s"
msgstr ""

#: system\protocols\irc\protocol.py:512
msgid "%s joined %s"
msgstr ""

#: system\protocols\irc\protocol.py:520
msgid "%s parted %s"
msgstr ""

#: system\protocols\irc\protocol.py:531
msgid "%s was kicked from %s by %s: %s"
msgstr ""

#: system\protocols\irc\protocol.py:549
msgid "%s has left IRC: %s"
msgstr ""

#: system\protocols\irc\protocol.py:580
msgid "%s sets mode %s: %s%s %s"
msgstr ""

#: system\protocols\irc\protocol.py:588
msgid "Mode change from irregular user: %s"
msgstr ""

#: system\protocols\irc\protocol.py:614
msgid "Rank mode %s set on invalid user %s in channel %s"
msgstr ""

#: system\protocols\irc\protocol.py:631
msgid "Topic for %s: %s (set by %s)"
msgstr ""

#: system\protocols\irc\protocol.py:705
msgid "%s is now known as %s"
msgstr ""

#: system\protocols\irc\protocol.py:783
msgid "RPL_ISUPPORT received: %s"
msgstr ""

#: system\protocols\irc\protocol.py:802
msgid " ===   MOTD   === "
msgstr ""

#: system\protocols\irc\protocol.py:805
msgid " === END MOTD ==="
msgstr ""

#: system\protocols\irc\protocol.py:856
msgid "Unable to join %s - Channel is invite-only"
msgstr ""

#: system\protocols\irc\protocol.py:864
msgid "Cannot do command '%s': %s"
msgstr ""

#: system\protocols\irc\protocol.py:874
msgid "%s created by %s (%s)"
msgstr ""

#: system\protocols\irc\protocol.py:908
msgid "VHOST set to %s by %s"
msgstr ""

#: system\protocols\irc\protocol.py:924
msgid "Invited to %s by %s."
msgstr ""

#: system\protocols\irc\protocol.py:930
msgid "Automatically joining %s.."
msgstr ""

#: system\protocols\irc\protocol.py:1053
msgid "Unexpected status in WHO response for user %s: %s"
msgstr ""

#: system\protocols\irc\protocol.py:1072
msgid "Lost track of user: %s"
msgstr ""

#: system\protocols\irc\rank.py:53
msgid "First argument must be of type Rank or all arguments must be given"
msgstr ""

#: system\protocols\irc\user.py:37
msgid "Tried to remove non-existent channel \"%s\" from user \"%s\""
msgstr ""

#: system\protocols\mumble\protocol.py:146
msgid "Attempting to load certificate file"
msgstr ""

#: system\protocols\mumble\protocol.py:151
msgid "Certificate file does not exist - generating..."
msgstr ""

#: system\protocols\mumble\protocol.py:197
msgid "Loaded specified certificate file"
msgstr ""

#: system\protocols\mumble\protocol.py:200
msgid "Could not import OpenSSL - cannot connect with certificate file"
msgstr ""

#: system\protocols\mumble\protocol.py:203
msgid "Could not load cert file"
msgstr ""

#: system\protocols\mumble\protocol.py:205
msgid "Unknown error while loading certificate file"
msgstr ""

#: system\protocols\mumble\protocol.py:210
msgid "No certificate specified - connecting without certificate"
msgstr ""

#: system\protocols\mumble\protocol.py:215
msgid "Disconnecting: Protocol shutdown"
msgstr ""

#: system\protocols\mumble\protocol.py:219
msgid "Connected to server."
msgstr ""

#: system\protocols\mumble\protocol.py:279
msgid "Message ID not available."
msgstr ""

#: system\protocols\mumble\protocol.py:286
msgid "Need to fill data"
msgstr ""

#: system\protocols\mumble\protocol.py:299
msgid "Exception while handling data."
msgstr ""

#: system\protocols\mumble\protocol.py:320
msgid "Connected to Murmur v%s"
msgstr ""

#: system\protocols\mumble\protocol.py:325
msgid "Could not connect to server: %s - %s"
msgstr ""

#: system\protocols\mumble\protocol.py:370
msgid "===   Welcome message   ==="
msgstr ""

#: system\protocols\mumble\protocol.py:373
msgid "=== End welcome message ==="
msgstr ""

#: system\protocols\mumble\protocol.py:423
msgid "User left: %s"
msgstr ""

#: system\protocols\mumble\protocol.py:442
msgid "Unknown message type: %s"
msgstr ""

#: system\protocols\mumble\protocol.py:443
msgid ""
"Received message '%s' (%d):\n"
"%s"
msgstr ""

#: system\protocols\mumble\protocol.py:473
msgid "Channel link: %s to %s"
msgstr ""

#: system\protocols\mumble\protocol.py:482
msgid "New channel: %s"
msgstr ""

#: system\protocols\mumble\protocol.py:486
msgid "Channel link added: %s to %s"
msgstr ""

#: system\protocols\mumble\protocol.py:499
msgid "Channel link removed: %s from %s"
msgstr ""

#: system\protocols\mumble\protocol.py:526
msgid "User joined: %s"
msgstr ""

#: system\protocols\mumble\protocol.py:543
msgid "No channel with id '%s'"
msgstr ""

#: system\protocols\mumble\protocol.py:550
msgid "No channel with name '%s'"
msgstr ""

#: system\protocols\mumble\protocol.py:553
msgid "No channel found in config"
msgstr ""

#: system\protocols\mumble\protocol.py:555
msgid "Config is missing 'channel' section"
msgstr ""

#: system\protocols\mumble\protocol.py:565
msgid "User moved channel: %s from %s to %s by %s"
msgstr ""

#: system\protocols\mumble\protocol.py:580
msgid "User was muted: %s by %s"
msgstr ""

#: system\protocols\mumble\protocol.py:583
msgid "User was unmuted: %s by %s"
msgstr ""

#: system\protocols\mumble\protocol.py:593
msgid "User was deafened: %s by %s"
msgstr ""

#: system\protocols\mumble\protocol.py:596
msgid "User was undeafened: %s by %s"
msgstr ""

#: system\protocols\mumble\protocol.py:605
msgid "User was suppressed: %s"
msgstr ""

#: system\protocols\mumble\protocol.py:607
msgid "User was unsuppressed: %s"
msgstr ""

#: system\protocols\mumble\protocol.py:616
msgid "User muted themselves: %s"
msgstr ""

#: system\protocols\mumble\protocol.py:618
msgid "User unmuted themselves: %s"
msgstr ""

#: system\protocols\mumble\protocol.py:627
msgid "User deafened themselves: %s"
msgstr ""

#: system\protocols\mumble\protocol.py:629
msgid "User undeafened themselves: %s"
msgstr ""

#: system\protocols\mumble\protocol.py:639
msgid "User was given priority speaker: %s by %s"
msgstr ""

#: system\protocols\mumble\protocol.py:643
msgid "User was revoked priority speaker: %s by %s"
msgstr ""

#: system\protocols\mumble\protocol.py:654
msgid "User started recording: %s"
msgstr ""

#: system\protocols\mumble\protocol.py:656
msgid "User stopped recording: %s"
msgstr ""

#: system\protocols\mumble\protocol.py:824
msgid "Sending text message: %s"
msgstr ""

#: system\protocols\mumble\protocol.py:917
msgid "Channel: %s"
msgstr ""

#: system\protocols\mumble\protocol.py:918
msgid "Mute: %s"
msgstr ""

#: system\protocols\mumble\protocol.py:919
msgid "Deaf: %s"
msgstr ""

#: system\protocols\mumble\protocol.py:920
msgid "Suppressed: %s"
msgstr ""

#: system\protocols\mumble\protocol.py:921
msgid "Self mute: %s"
msgstr ""

#: system\protocols\mumble\protocol.py:922
msgid "Self deaf: %s"
msgstr ""

#: system\protocols\mumble\protocol.py:923
msgid "Priority speaker: %s"
msgstr ""

#: system\protocols\mumble\protocol.py:924
msgid "Recording: %s"
msgstr ""

#: system\protocols\mumble\protocol.py:940
msgid "Users {"
msgstr ""

#: system\storage\config.py:108 system\storage\data.py:101
msgid "Invalid callback supplied!"
msgstr ""

#: system\storage\config.py:162 system\storage\config.py:291
msgid "File not found: %s"
msgstr ""

#: system\storage\config.py:176 system\storage\config.py:305
#: system\storage\config.py:426 system\storage\data.py:186
#: system\storage\data.py:196 system\storage\data.py:350
#: system\storage\data.py:359 system\storage\data.py:479
#: system\storage\data.py:489
msgid "Error running callback %s"
msgstr ""

#: system\storage\config.py:208 system\storage\config.py:345
#: system\storage\data.py:250 system\storage\data.py:555
msgid "Error writing file"
msgstr ""

#: system\storage\config.py:234 system\storage\config.py:237
#: system\storage\config.py:371 system\storage\config.py:374
#: system\storage\config.py:455 system\storage\config.py:458
msgid "Configuration objects are read-only!"
msgstr ""

#: system\storage\data.py:260
msgid ""
"# This is the data in memory, and may not actually be what's in the file.\n"
"\n"
"%s"
msgstr ""

#: system\storage\data.py:709
msgid "Parsed module: %s"
msgstr ""

#: system\storage\files.py:45
msgid "Type '%s' is unknown or not supported for %s files."
msgstr ""

#: system\storage\files.py:65
msgid "This file is not ready for use."
msgstr ""

#: system\storage\files.py:74
msgid "Only the storage manager can make a file ready."
msgstr ""

#: system\storage\files.py:81
msgid "Only the storage manager can set the file owner."
msgstr ""

#: system\storage\files.py:97
msgid "Only the storage manager can release files."
msgstr ""

#: system\storage\manager.py:70 system\storage\manager.py:111
#: system\storage\manager.py:121
msgid "Data file %s is owned by another object."
msgstr ""

#: system\storage\manager.py:87
msgid "Config file %s is owned by another object."
msgstr ""

#: system\storage\manager.py:101 system\storage\manager.py:129
msgid "Unknown storage type: %s"
msgstr ""

#: utils\console.py:37
msgid "Unable to get the size of this terminal."
msgstr ""

#: utils\console.py:134
msgid "Loaded: %s, %s"
msgstr ""

#: utils\console.py:155
msgid "Loaded: %s"
msgstr ""

#: utils\irc.py:59
msgid "Hostmask must be in the form '*!*@*'"
msgstr ""

#: utils\irc.py:141
msgid "Invalid case mapping: %s"
msgstr ""

#: utils\log.py:278
msgid "*** LOGFILE OPENED: %s ***"
msgstr ""

#: utils\log.py:311
msgid ""
"*** LOGFILE CLOSED: %s ***\n"
"\n"
msgstr ""

#: utils\misc.py:70
msgid "Word %s is longer than %s characters"
msgstr ""

